### ISSUE TITLE
3 minute delay before starting a manual sort

### ISSUE THREAD

**Issue by Gitoffthelawn** [eric-bixby/auto-sort-bookmarks-webext#100]
Hi Eric!  I hope you are staying healthy.

What is the purpose of the 3 minute delay before ASB begins a manual sort?

Is it still necessary/advised?

**Comment by eric-bixby** [comment]
It only waits for activity to stop before sorting. It shouldn’t be 3 minutes unless you have something like a bookmark sync causing it.

**Comment by Gitoffthelawn** [comment]
Sorry, I'm confused.  What's the function of the timer with a 3 minute minimum if it's just waiting for activity to stop?

(BTW, I thought I had to wait about 6 minutes for it to start, and I don't have sync enabled.)

**Comment by eric-bixby** [comment]
The minimum is 3 seconds, not minutes.

**Comment by eric-bixby** [comment]
The purpose is to determine that the user is no longer making changes (inactivity) because there could be corruption if sorting and user changed happen at the same time.

**Comment by Gitoffthelawn** [comment]
Thanks so much Eric.  I appreciate your help.
