### ISSUE TITLE
Configuration Window is Blank

### ISSUE THREAD

**Issue by DontKnowJack** [eric-bixby/auto-sort-bookmarks-webext#102]
Hi, Eric.

I paused using AutoSort Bookmark for a few months even though I was using it manually on a regular basis. Today I re-enabled it. 

My settings are just as the were. But when I go to Configure Folders, the screen is blank except for these words: "Folders to Sort: Uncheck the folders to exclude when sorting."

I waited quite a while in case it was trying to gather info to populate. Then I disabled ALL other Extensions except  AutoSort Bookmark. And I restarted Firefox. I also selected Auto-sort: and then I de-selected it. All resulted in the same blank Config window.

I have the latest Firefox 79.0 on a Mac.

What can I do to resurrect this great program?

Thanks

**Comment by eric-bixby** [comment]
It works fine for me on a mac.  You're going to need to do a little debugging.

1) Open the "Configure Folders" tab.
2) Click on the menu icon, then Web Developer, then Web Console.
3) You should see some stuff about "PREFS_SPEC_UPDATED" and "PREFS_UPDATED".

If you don't see that or you see something entirely different, then reply with the output.

1) Right-click on the text
2) Select-all
3) Select copy message

**Comment by DontKnowJack** [comment]
I'm seeing exactly what you are suggesting I should see.
[Screen Shot 2020-08-23 at 6.46.23 PM.pdf](https://github.com/eric-bixby/auto-sort-bookmarks-webext/files/5115371/Screen.Shot.2020-08-23.at.6.46.23.PM.pdf)

**Comment by DontKnowJack** [comment]
In addition to what I just sent you, I did some other testing.

I have an ancient FF profile I was about to discard. So I opened it in FF 79.0 and all worked as it should.

I also have an ancient version of FF 54.0.1 that I used to open that successful profile. That also worked.

And I used FF 79.0 to open a test profile, which worked.

So something is wrong with my profile.

The one thing that I am wondering is the number of windows and tabs I have open for my projects.

I have 15 windows and 164 total tabs.

Could that be the cause? If not, what can I do to fix the profile? I have a huge number of bookmarks and organization I don't want to lose.

**Comment by eric-bixby** [comment]
Yes, that makes sense.  It's most likely your profile/preference but I have no idea what is actually causing it.

I've experienced problems with the profile/preferences myself.  The best thing to do is start over with a fresh profile.  Trying to figure out which profile preference is causing the problem can be time-consuming.  I know losing your custom settings is a pain but it's the most reliable way I know of to resolve it.

Adding/removing/changing add-ons and preferences over time eventually leads to problems.  However, I don't think the number of windows/tabs is the problem in this case.

**Comment by DontKnowJack** [comment]
Thanks for helping me with this, Eric.

I tried various methods to get a new profile up and running in the easiest and shortest time.

That included the Refresh Firefox method and Firefox’s “Recovering Important Data from an Old Profile” page.

Auto Sort Bookmarks produced the same results. 

So I tried to save my bookmarks so I could import them into the new profile. FF would not save them no matter what incantation I used.

So I decided to try the new shell profile approach with only the bookmarks in it. Well, I could not find what that bookmark file was. But just before giving up, I learned it is places.sqlite. So I put that into the shell profile and got my bookmarks back as before.

Then I used MySessions addon to recreate my open Windows and Tabs.

Because I could have two profiles open at the same time, I then recreated my password one at a time. Unfortunately, I have collected an amazingly large number over the years, since at lease 2012. Fortunately, the vast majority have been over a year since I accessed them. So I left them alone.

I tested the Configuration Window of Auto Sort Bookmarks at each step in this process. And now it is working fine.

Because there is no Progress Bar to let me know how long the sorting is taking, I do wonder how do I know when it is done? I don’t use my browser for a while so as not to interfere with it.

I just submitted a review: “Works quite well, and Eric gave quick support. Excellent!”

Thanks again, Eric.

**Comment by eric-bixby** [comment]
@DontKnowJack,

Glad you figured it out.

Although, I'm surprised you weren't able to backup or export your bookmarks.  This might be a bug in Firefox.  You might have been able to do this next time:
https://support.mozilla.org/en-US/kb/cant-add-change-or-save-bookmarks

Yes, I agree a progress indicator would be nice.  I was going to try changing the toolbar icon while sorting, but I don't think Firefox lets add-on do this.  However, you can change the color, so I might do that.  I'm also thinking of adding logging back so you can see what it's doing (like sorting) and this will also help with debugging.

Thanks for the positive review.
