### ISSUE TITLE
Sorting Bookmarks in-between Folders

### ISSUE THREAD

**Issue by VeraLucius** [eric-bixby/auto-sort-bookmarks-webext#104]
Hey, first of all great extension!

I have a feature request. I'd really like to have a set amount of bookmarks in my Firefox Bookmarks Toolbar (or any other folder?), containing only bookmarks with the highest access counts (or other criteria?) across preselected folders. 

Thanks

**Comment by eric-bixby** [comment]
I think what you might be looking for already exists in Firefox, but is an advanced/hidden feature.  It's called a "smart bookmark".  The two that I know of are "most visited" and "recently visited".

Here are links for creating a "smart bookmark":
https://support.mozilla.org/bm/questions/1241336
https://support.mozilla.org/en-US/questions/1301502
