### ISSUE TITLE
Expand All Folders Button on Configure Folders

### ISSUE THREAD

**Issue by megamorphg** [eric-bixby/auto-sort-bookmarks-webext#111]
I have a lot of folders and having to click the tiny plus button on every single one to configure exclusion on them is painful, especially when I am troubleshooting issues with the Exclusion not staying by restoring bookmarks (so that I can show you).

Please provide an option on the Configure Folders to "Expand All Folders".

**Comment by eric-bixby** [comment]
Duplicate of #103
