### ISSUE TITLE
Manual Sorting when Order by Last Modified

### ISSUE THREAD

**Issue by siran** [eric-bixby/auto-sort-bookmarks-webext#12]
Some times I just want a folder/bookmark in a certain order, so I drag it in place, but the add-on reorders it (I order by Last Modified inverse).

This could maybe fixed if dragging/dropping a folder/bookmark changed the Last Modified property

**Comment by eric-bixby** [comment]
This issue is resolved using ASB 3.1 and Firefox 57.  Firefox updates last-modified when you move a bookmark.
