### ISSUE TITLE
Black Icon Not Seen on Black Background

### ISSUE THREAD

**Issue by eric-bixby** [eric-bixby/auto-sort-bookmarks-webext#33]
I had changed the icon color from gray/grey to black, which is fine for a light colored background, but not good for a dark colored background.  I'd like the icon to change like the Firefox toolbar icons which automatically adjust from black to white based on the background color.  I couldn't find the documentation for this feature.  If anyone knows, please let me know.

In the meantime, I was thinking of doing a circular or rectangular filled area of red, white, or blue.

**Comment by Gitoffthelawn** [comment]
Or restore the gray icon. :)

The gray icon matched all the other native icons when it was placed in Firefox's menu panel.  Unfortunately, the black icon doesn't match any of the browser's native icons.

**Comment by eric-bixby** [comment]
It might depend on your platform/monitor, but for me, and report by others, the gray icon is too light and looks like a disabled icon.

**Comment by Gitoffthelawn** [comment]
I agree.  The default gray icons chosen by Mozilla are all very light.  I think they were trying to make them blend into the background to be less intrusive.  But when one icon is dark (how Auto-Sort Bookmarks is now) and the others are light, it makes it look like all the others are disabled.

It's an odd UI/UX conundrum Mozilla has created.

Here's a possible solution: When Auto-Sort Bookmarks is in *auto* mode, use a high contrast icon, and when it is *manual* mode, use the gray icon.

**Comment by eric-bixby** [comment]
I'm thinking something like the following...
![icon-16](https://cloud.githubusercontent.com/assets/5050673/17880914/7c0866c8-68b5-11e6-815c-c37fda2105b0.png)
![icon-32](https://cloud.githubusercontent.com/assets/5050673/17880912/7bfdbf66-68b5-11e6-819e-d1aceda04a5a.png)
![icon-64](https://cloud.githubusercontent.com/assets/5050673/17880913/7bff72e8-68b5-11e6-96dd-bc18516e77db.png)

I'd like to use a different color for manual vs. automatic sorting mode and maybe one more color when the sorting is in progress.

**Comment by Gitoffthelawn** [comment]
> I'd like to use a different color for manual vs. automatic sorting mode and maybe one more color when the sorting is in progress.

:+1: 

I wish I had the time right now, but I'd like to make a new icon altogether.  The arrow icon is too similar to the native Firefox download icon.  I do at like the big arrow more than the all-too-common "A...Z" icons that aren't really appealing for this extension.

**Comment by digitalcircuit** [comment]
If there's no way to tap into background-color dependent icons like Firefox does, I'd suggest an icon that's more "flat" instead of glossy or highlighted, since that seems more out of place next to the other icons.

Here's a screenshot with an example of a few other icons, though these aren't perfect either :)
![firefox - auto sort bookmarks all icons on linux](https://cloud.githubusercontent.com/assets/1449717/17909168/db905aa4-6948-11e6-844c-bbbe0cab3be9.png)

It might also work to add a preference for choosing an icon style (*colored, light, dark*).

**Comment by eric-bixby** [comment]
Unfortunately, it will never be perfect because everyone has different tastes.  That's why I'd prefer to keep it as simple and neutral as possible.  I'll probably just update the color/colour (US/UK) to more closely match the default Firefox style.

Meanwhile, I will keep searching the Mozilla SDK, there must be a way of detecting the theme background color, then I can pragmatically change the icon used.

**Comment by eric-bixby** [comment]
Version 3.0 has a new icon.
