### ISSUE TITLE
'Delay Before Auto-Sort' not Working Correctly

### ISSUE THREAD

**Issue by NondescreptUser** [eric-bixby/auto-sort-bookmarks-webext#41]
Auto-sort was trying to sort bookmarks/folders while I was editing them, so I thought, "I'll just increase the delay time to allow me plenty of time." So I increased both the bookmark delay before sort and folder delay before sort settings to 55 seconds. To my surprise, the extension still begins to sort after around 3-5 seconds.

Is this a bug? Or is the delay specified in milliseconds? (It says seconds in the description, though.) Or am I the only one with this issue? I'm currently using Firefox version 49.0.2 and Auto-sort Bookmarks version 2.1.0.9 on Windows 7 Pro.

**Comment by eric-bixby** [comment]
Yes, it is a bug.  I was going to address this in issue #30, but I'll do that in this issue instead.

**Comment by eric-bixby** [comment]
This issue has been addressed in version 3.0
