### ISSUE TITLE
Port to WebExtensions API (support Firefox Quantum, version 57)

### ISSUE THREAD

**Issue by eric-bixby** [eric-bixby/auto-sort-bookmarks-webext#45]
@EMLVIRUS: You might find this interesting based on your request to have this add-on support Chrome in issue #38.

Based on the following article, it appears the Mozilla wants to require add-ons use the WebExtensions API:
https://www.bleepingcomputer.com/news/software/the-future-of-firefox-add-ons/

FYI...information about WebExtensions:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions

**Comment by EMLVIRUS** [comment]
Currently, Web Extension requires any extension injects code on website-based level (that's why it got its name) instead of accessing browser's files (including bookmarks folder in user's profile) directly.
conclusion: if Web Extension doesn't complement at all in this way, this addon is likely to be abandoned.

**Comment by eric-bixby** [comment]
Unfortunately, yes.  If the WebExtensions doesn't provide the capabilities that this add-on needs, then this add-on will not be supported by the November 2017 release of Firefox.  However, it may live on in Firefox ESR and PaleMoon.
http://www.palemoon.org/

**Comment by yfdyh000** [comment]
https://developer.mozilla.org/Add-ons/WebExtensions/API/Bookmarks/ are have some APIs.

The https://chrome.google.com/webstore/detail/supersorter/hjebfgojnlefhdgmomncgjglmdckngij looks work with Chrome Store Foxified.

**Comment by eric-bixby** [comment]
My plan is to port the main branch of this add-on to WebExtensions.  I will do this as beta releases (so hopefully, I can get some beta testers to sign-up).

Since PaleMoon doesn't plan to support WebExtensions, I will need to update the PM branch:
https://github.com/antoyo/auto-sort-bookmarks/tree/palemoon

I tried ChromeStoreFoxified on a different Chrome add-on and it didn't work, so WebExtensions is getting Firefox closer to Chrome, but it's not 100% yet.

**Comment by yfdyh000** [comment]
>so WebExtensions is getting Firefox closer to Chrome, but it's not 100% yet.

Yes, see http://arewewebextensionsyet.com/.

**Comment by eric-bixby** [comment]
I saw that site, thanks, it is useful to see the progress.

**Comment by Taurean75** [comment]
Any progress?

**Comment by eric-bixby** [comment]
Yes, I started months ago, but got distracted.  I'll try to get back to
it.  However, I'm frankly disillusioned about porting because there are
existing chrome alternative that could work on Firefox with a little
tweaking.  Therefore, I'm considering working with the author of a chrome
add-on to make their add-on also work on Firefox.

**Comment by Taurean75** [comment]
Hmmm, I can't find any good ones on Chrome Store.

**Comment by eric-bixby** [comment]
IMHO, I like sprucemarks:
https://github.com/ForestMist/sprucemarks

**Comment by heftig** [comment]
Thanks for supporting us this far. Two years of sorted bookmarks for me.

I've cobbled together a replacement this weekend:
https://addons.mozilla.org/en-US/firefox/addon/sort-bookmarks-webext/

Mostly for myself, I admit. It's definitely not at feature parity.

**Comment by eric-bixby** [comment]
That's cool.

**Comment by Taurean75** [comment]
heftig, could you add an option for "sort by visit count."

**Comment by Taurean75** [comment]
heftig, is it possible to sort by last visited bookmark?  This is what I use this add-on for.

**Comment by eric-bixby** [comment]
I'll work on the port this weekend. I haven't given up on Mozilla/Firefox
yet. We need to have compition.

Anyone want to be a beta tester?

**Comment by Taurean75** [comment]
I can.  BTW, I've some programming experiences but not in JavaScript unfortunately.

**Comment by eric-bixby** [comment]
Great, thanks.  No coding experience needed.  I just need someone to keep
me honest (make sure I didn't break anything) before I officially release
it.

I'll send you an email every time I publish a beta release.  I think I'll
create a wiki page to track issues (with the beta; need to keep them
separated from issues for normal releases).

**Comment by EMLVIRUS** [comment]
@eric-bixby why not post a pre-release on GitHub so that people will decide if they will test.

**Comment by eric-bixby** [comment]
@EMLVIRUS: Yes, that's what I'm planning to do (use the pre-release feature), except I just need one person (more is even better) to provide me feedback (or reassurance) that at lease one person has tried it and their browser didn't crash.  I definitely want it easy for anyone to try the pre-release.

**Comment by eric-bixby** [comment]
I changed my mind.  I'll keep it completely open.  I'll just post the pre-release and not wait for feedback.  If @Taurean75 checks it out, then great.  If he doesn't, then that's fine too.  I'll just be sure to give people a chance to try it before doing a normal release.

**Comment by Taurean75** [comment]
Okay, fine with me.

**Comment by eric-bixby** [comment]
I posted my first beta release:
https://github.com/antoyo/auto-sort-bookmarks/releases/tag/v3.0beta1

Enter "about:debugging" into location bar, then load the .xpi file.

No sorting yet.  This just shows the settings page.

**Comment by EMLVIRUS** [comment]
Nothing wrong here.

**Comment by eric-bixby** [comment]
Cool, thanks.

**Comment by Taurean75** [comment]
Nothing wrong here, either.

**Comment by Taurean75** [comment]
Are you gonna add an option to select which folders to sort?

**Comment by eric-bixby** [comment]
Yes. I'll add a button somewhere to configure the excluded folders.

**Comment by Hubfront** [comment]
Thank you for porting to Webextensions, to make this great add-on live on.

**Comment by davidhedlund** [comment]
@antoyo Is Auto-Sort Bookmarks a [hybrid WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) yet?

**Comment by antoyo** [comment]
@davidhedlund I'm not maintaining this add-on anymore. Please ask @eric-bixby.

**Comment by Rictusempra** [comment]
@antoyo I am clear that it is out of my business, but I suggest transferring

**Comment by eric-bixby** [comment]
@davidhedlund Yes, I'll work on that next.

**Comment by eric-bixby** [comment]
@antoyo If you decide to transfer to me, then please use an alternate name of "auto-sort-bookmarks-webext" because I already have a fork in my repo.

**Comment by davidhedlund** [comment]
@eric-bixby I'll be happy to move Auto-Sort Bookmarks from https://directory.fsf.org/wiki/Free_Software_Directory:IceCat_extensions_(proposed)/WebExtensions#Multiprocess to https://directory.fsf.org/wiki/Free_Software_Directory:IceCat_extensions_(proposed)/WebExtensions#WebExtensions

**Comment by eric-bixby** [comment]
Sounds good, thanks

**Comment by davidhedlund** [comment]
An add-on is a hybrid WE if it has a "hasEmbeddedWebExtension" key available in the install.rdf, its not found in the current version of Auto-Sort Bookmarks.

I didn't know that was the standard procedure when I asked, sorry.

**Comment by eric-bixby** [comment]
I see.  I need to re-read the instruction for making an embedded web
extension, then I'll submit an update. Hopefully it won't take me long.

**Comment by davidhedlund** [comment]
@eric-bixby Thank you for your support, and good luck.

**Comment by antoyo** [comment]
@Rictusempra @eric-bixby What do you mean by transferring? Transferring the repo?
If so, I have no issues with doing that.

**Comment by Rictusempra** [comment]
@antoyo Yes. Since that will give @eric-bixby more convenience. And as he says:
>please use an alternate name of "auto-sort-bookmarks-webext" because I already have a fork in my repo.

**Comment by antoyo** [comment]
I renamed the repository but I still cannot transfer it, I get the following error:

> eric-bixby already has a repository in the antoyo/auto-sort-bookmarks-webext network

What should I do to transfer the repository?

**Comment by Rictusempra** [comment]
Maybe @eric-bixby should delete its own fork first.

**Comment by eric-bixby** [comment]
@antoyo I have deleted my fork, please try the transfer again.

**Comment by eric-bixby** [comment]
@antoyo Thanks, the transfer worked with no problems.

**Comment by havrancek** [comment]
hello, any news?

**Comment by eric-bixby** [comment]
I created a hybrid version for migrating prefs from the legacy API to web-ext.  I got stuck trying to figure out how weh (web-extension-helper) stores the prefs.  Looks like it's a list of name/value pairs that is save in local-storage.  I was trying to find a dev tool to show me what the data looks like.  Mozilla provides a dev tool (previously called FireBug) for doing inspection.  I'm just having problems getting it to work (I don't see the data).  It may be that since the add-on is temporarily installed then the prefs don't actually get saved to storage.

**Comment by Taurean75** [comment]
In that case, how about working on other parts first...?

**Comment by eric-bixby** [comment]
I'm no longer blocked, I was able to get my question answered on the web-ext-support mailing list:
https://mail.mozilla.org/listinfo/webextensions-support

Anyway, I'll try to post another beta release this weekend.

**Comment by Taurean75** [comment]
Any updates?

**Comment by eric-bixby** [comment]
I've been working on it.  Once I have manual sorting working, then I'll post another beta release.  I decided to skip doing a embedded/hybrid release and just focusing on porting.

**Comment by eric-bixby** [comment]
Due to a typo in my .eslintrc, I'm also upgrading from es5 to es6.  I wasn't planning to but since there's some nice features in es6, I figured I may as well upgrade.

**Comment by havrancek** [comment]
great, when i will be ready?

**Comment by eric-bixby** [comment]
The goal is to be finished before the end of November.  Ideally, I'll be able to release a couple beta releases before then.

**Comment by Taurean75** [comment]
No beta release?

**Comment by eric-bixby** [comment]
I'm planning another beta release this weekend.

The two remaining hurdles are:
1) port to browser.bookmarks.getChildren() API.
2) exclude folders feature: create new code for annotations/tags.

For #2, since tags work differently in the chrome API, I think this will take more work, so I'm going to skip it for the 3.0 release and concentrate on the auto/manual sorting (#1).

**Comment by eric-bixby** [comment]
Still not sorting yet.  I got the getChildren() call working.  Except it's async, so still need to do some more work to get the flow right.  It tries to sort, before the getChildren() finishes, thus there is nothing to sort.

**Comment by defmonk0** [comment]
The getChildren function seems to return a promise. You have a couple options from there for reacting to it. Using the standard [promise->then](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then) syntax, or using [await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await). It's up to you on which one you prefer. 

Assuming you weren't using the promise syntax before, using promise->then is likely much easier since await generally is a bit harder to make clean code without planning for it in the code structure from the start.

A simple example:

```Javascript
// Just using the id supplied in the example from MDN.
var bookmarkPromise = bookmarks.getChildren("unfiled_____");

bookmarkPromies.then(
	function(children) {
		// Simple name sort for example.
		// Can use child.type to sort folders and stuff first.
		children.sort(function(a, b) {
			return a.title.localeCompare(b.title);
		});

		// Continue the rest of your code here...
		// The children should be properly sorted.
	},
	function(err) {
		console.error("Couldn't get children. Error: " + err);
	}
);
```

**Comment by eric-bixby** [comment]
@defmonk0: I agree, thanks, I'll do that.  I actually had added a call using the promise->next syntax, but was getting an error.  In chrome, it appears that the id passed to getChildren() must be a string.  Whereas, in MDN, id was an int/number.  Anyway, I ran out of time debugging that issue.

**Comment by defmonk0** [comment]
Ah. Yea. Small inaccuracies in documentation like that are the worst. 

Well, good luck. I and I'm sure many others are waiting patiently. Quantum may have released today, but none of the alternatives to this extension quite manage everything this was doing. I look forward to the day my bookmarks are once again alphabetized. Lol.

**Comment by eric-bixby** [comment]
You are right, Firefox 57/Quantum is now available.  I thought I had one more week.  I'll try to spend more time on it.

**Comment by MeiGuddet** [comment]
I like this addon and will patiently wait 👍

**Comment by eric-bixby** [comment]
Someone please try beta4:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.0beta4
(you'll need to type "about:debugging" into the address-bar in order to load it).

This version does sorting using default preferences (preferences not working yet).

**Comment by Selmi** [comment]
it seems it is working, hard to do anything special with it when there are not preferences
tested on 57.0 x64 from linux ubuntu repository

**Comment by eric-bixby** [comment]
Cool, thanks.  Yes, I'm working on preferences now.  Once that works, then I can release it.

**Comment by eric-bixby** [comment]
I've released version 3.0 to AMO.

**Comment by Taurean75** [comment]
Thanks for the update; however, many sort criteria seem to be missing. Are you going to add "last visited" criteria soon? Without that, this extension is useless to me.

**Comment by eric-bixby** [comment]
@Taurean75 : Yes, if there is an API available for this.  See issue #55

**Comment by georgthegreat** [comment]
Hi.

It looks like new extension ignores sorting "Other bookmarks" folder (where new bookmarks are being added bt defaut).

**Comment by zaphmann** [comment]
Hi Eric, very interesting reading and much appreciated effort on your part and others. What's the state of play? Is there an alternative that does "last visited" and "most visited", or do you think you will get that feature back sometime?

**Comment by eric-bixby** [comment]
See issue #55
