### ISSUE TITLE
Feature request: Sort by Domain (not url)

### ISSUE THREAD

**Issue by xernon** [eric-bixby/auto-sort-bookmarks-webext#46]
I would like to request a Sort by Domain feature, that way i could for example make it sort YouTube videos by Last Modified, since they don't have meaningful URLs.

**Comment by eric-bixby** [comment]
Since the domain is part of the URL.  How about sorting by the URL and then sorting by Last Modified?

**Comment by xernon** [comment]
well, i am quite lazy, so the whole point is simply click star and let it do the work :)

**Comment by eric-bixby** [comment]
There is a beta release available for testing:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases

**Comment by eric-bixby** [comment]
Added to version 3.4
