### ISSUE TITLE
Feature request: automove a new bookmark to its Domain folder(if assigned)

### ISSUE THREAD

**Issue by xernon** [eric-bixby/auto-sort-bookmarks-webext#47]
Since new bookmarks go (if not further selected) into the "Other Bookmarks" folder, it would be nice, if bookmarks for some Domains (like YouTube or 9GAG) would automatically go into a specified folder. It can be a separated editable list (example: youtube.com; 9gag.com;...)

**Comment by eric-bixby** [comment]
Maybe. I'm hesitant because it's kind of outside the scope of sorting.  Moving/filtering is related, but it might be covered by another add-on.

For example, I use "Add Bookmarks Here 2", maybe this does what you are looking for:
https://addons.mozilla.org/en-US/firefox/addon/add-bookmark-here-2/

**Comment by xernon** [comment]
That addon is pretty close to it, but it isn't simply clicking Star, one has to navigate first.
Besides, i would have to sort out my Other bookmarks list. :)
Well, I see that it isn't a simple request, so if it won't be done, no hard feelings, it is still very useful after all.

To those that want to try "Add Bookmarks Here 2", it adds a Button in to folders to put a bookmark there, with some other options around it(no sorting).

**Comment by eric-bixby** [comment]
Sorry, I'm going to close this request as I don't think I will ever get to it.
