### ISSUE TITLE
Feature request: Sort by "frecency"

### ISSUE THREAD

**Issue by Kantfnas** [eric-bixby/auto-sort-bookmarks-webext#48]
Firefox has this excellent ranking system called "frecency" (portmanteau of frequency and recency), which it uses to rank suggestions when you type in the address bar. I think this would be a great way to order bookmarks as well! The algorithm is all there and the ranking is continuously updated in the moz_places table.

Some information on the frecency algorithm used [here](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Frecency_algorithm).

**Comment by eric-bixby** [comment]
Would this be the same as "Sort by Most Recent Visit" or "Sort by Visit Count" using the Firefox sort feature?

**Comment by Mullenuh** [comment]
Sorry about my delayed answer. The notification was filtered out somehow.
No, it would not. "Most recent visit" sorts by the latest date of visit (column last_visit_date), whereas "Sort by visit count" sorts by, well, the sheer count of visits (column visit_count). The column "frecency" contains a metric which is a clever combination of the two, which decreases slowly if, for example, there is a place you used to visit often but don't anymore, and hence has a high visit_count but isn't very relevant. As far as I can see, there is no such manual sorting feature in Firefox, but the frecency rather works "behind the scenes", adding relevance to each item in the search/address bar.

**Comment by eric-bixby** [comment]
Sorry for the long delay.  Unfortunately, Firefox does not provide this information to add-ons.  Based on the following bug report, I don't think they ever will: https://bugzilla.mozilla.org/show_bug.cgi?id=411591
Therefore, I'm going to close this issue.
