### ISSUE TITLE
Add back missing sort criteria like "last visited" and "most visited"

### ISSUE THREAD

**Issue by eric-bixby** [eric-bixby/auto-sort-bookmarks-webext#55]
There were sort criteria, such as reverse-URL, description, etc. that was removed in version 3.0.

This was removed because it wasn't obvious how to get this information from the chrome (web-extension) API.

Need to add this back, if possible.

**Comment by Taurean75** [comment]
As I've said, I just need the "last visited" criteria. I hope it'd get implemented soon.

**Comment by sirbogs** [comment]
I'll second that ... last visited is by far the best way to sort bookmarks
:)

**Comment by zaphmann** [comment]
Hi Eric

Suddenly the sort by options have reduced to "name" and URL only... very confusing - I was using based on most used and last used. Now non-functional - will you be fixing this?
thanks
Zaph

**Comment by eric-bixby** [comment]
Yes, I'm investigating an update for "last visited" and "most visited".  Looks like the History API may support this.

**Comment by Taurean75** [comment]
[This](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/history/getVisits).

**Comment by eric-bixby** [comment]
I've released version 3.1 to address this issue.  Give it a try.
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.1

**Comment by Taurean75** [comment]
I can't use it before #54 is resolved as my bookmark toolbar is organized in a certain order.

I'm glad you were able to add more criteria, though.

**Comment by Taurean75** [comment]
@eric-bixby, I just saw the "sort folders by" option. With that unchecked, I can use this again, and it's working great!

One thing, though: Sorting is triggered only when I click / open the folder. Is this intended?

**Comment by zaphmann** [comment]
downloading from github ff wouldn't let me load the add-on as it is not signed

**Comment by eric-bixby** [comment]
Right, you need to type "about:debugging" into the address bar.  Then select the "Load Temp. Add-on" and select the downloaded .xpi file.  However, version 3.1 is available from Mozilla, just update your add-ons.

**Comment by Taurean75** [comment]
@zaphmann, get it  from AMO.

**Comment by zaphmann** [comment]
deleted it and got from tools - add-ons and it's working great! thanks

**Comment by Taurean75** [comment]
@eric-bixby, issue #54 really needs to be resolved.
