### ISSUE TITLE
Auto Sort Turns On by Manual Sort 

### ISSUE THREAD

**Issue by Taurean75** [eric-bixby/auto-sort-bookmarks-webext#57]
I turned it off in the settings, but it gets turned on when I click on "sort" via the toolbar button.

Thanks.

**Comment by eric-bixby** [comment]
I'm not able to reproduce this.

Did you remember to click on the Save button in the bottom right?  Before changes were immediate; now you have to save them for it to take effect.

**Comment by Taurean75** [comment]
I did.  Well, I'll wait until #54 is resolved.
