### ISSUE TITLE
CCleaner erases my settings

### ISSUE THREAD

**Issue by ladybug42** [eric-bixby/auto-sort-bookmarks-webext#58]
Does anyone know how to lock the settings or tweak CCleaner to ignore them?  I love the auto-sort bookmark manager and I am very glad to have it back on Firefox again but I really want to turn off Auto-Sort!
Thanks,

**Comment by eric-bixby** [comment]
I no longer use CCleaner myself since the security breach. Also, as you are finding, it cleans too much.

Anyway, I think you have to look under advanced settings, then Firefox. Either disable Firefox completely (my suggestion) or create an exclusion/rule for localStorage with an ID of sortbookmarks@bouanto

**Comment by ladybug42** [comment]
Thanks for the quick reply.  I could only find sortbookmarks@bouanto in Roaming, not Local.  I set an exclusion but it didn't seem to work; the app still keeps resetting to auto-sort after 3 seconds.  I usually want to customize the name of any new bookmark but it disappears down the list before I get a chance and I have to track it down before I can edit.  It's annoying but I will figure something out.

**Comment by eric-bixby** [comment]
It depends on how you add bookmarks.  I'd suggest clicking on the star icon in the address bar.  You''ll get a pop-up to edit the bookmark.  This also let's you move the bookmark to a different folder.

**Comment by ladybug42** [comment]
I'm in the habit of dragging them but I could get used to using the star.
Thanks for the suggestion.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
