### ISSUE TITLE
Poll: Should automatic sorting be on by default?

### ISSUE THREAD

**Issue by eric-bixby** [eric-bixby/auto-sort-bookmarks-webext#60]
I'm curious to find out what most people think the default setting should be for auto-sort.  The user is able to change the setting and should only need to do so once.  However, if tools like CCleaner reset your settings, then the user has to change this setting every time.  This will also tell me if most people use the auto-sort feature.

Please take one second to give me your feedback:
https://www.surveymonkey.com/r/738YXJH

I'll go with what the majority think.

**Comment by digitalcircuit** [comment]
If you do change it to not auto-sort by default, you may want to make it a bit more obvious how to enable it.  Perhaps in the extension popover/icon, alongside the `Sort` and `Settings` buttons, a small label could indicate that `Auto-sort is`_`off`_ or _`on`_ with a toggle link, or some other guidance.  (I am not a UI designer.)

In my biased opinion, if auto-sort happens without any interaction after installing, that might be unexpected - you won't have a chance to change sort order or configure ignore rules, which could mess up one's organization.

And issue #13 (syncing settings) should further lessen how often this matters (except for those who don't want settings to sync).

**Comment by eric-bixby** [comment]
I agree, after installing, the user might not expect something to happen right away.

Therefore, I'll set auto-sort off by default, but make the settings/preference page show up so the user can decide.

**Comment by digitalcircuit** [comment]
That sounds like a good idea!

Note for the future if/when implementing settings synchronization: if possible, you'll want to delay the auto-open settings page until after the first sync.  That way, the person's not asked to configure when Firefox Sync installs the addon on their other devices.

This doesn't happen very often (new device/first time using addon), so don't give it that much priority :)

**Comment by eric-bixby** [comment]
Poll results: the winning answer is "No" -- the default will be to disable auto-sort by default.

![poll_results](https://user-images.githubusercontent.com/5050673/33811188-7ef0fe74-ddc4-11e7-8c92-cef12c955a60.png)
