### ISSUE TITLE
Sorting Bookmarks not working correctly.

### ISSUE THREAD

**Issue by Hawkeye58** [eric-bixby/auto-sort-bookmarks-webext#62]
I have setup my settings to sort as follows:

Last Visited, inverse order and then Access Count, inverse order, see screenshot attached.

However, as you can see from the screenshot of my bookmarks, this sort is not working correctly, even though I selected the option to Sort manually.

![auto-sort settings](https://user-images.githubusercontent.com/34255678/33583720-c4116c50-d9af-11e7-9466-02bf2214e294.jpg)

![auto-sort bookmarks](https://user-images.githubusercontent.com/34255678/33583726-c9d0e63e-d9af-11e7-97b6-2ea6b58321d5.jpg)

**Comment by Taurean75** [comment]
@Hawkeye58, do those sites redirect you to "https" and your bookmarks contain "http"?  In this case, I found it not sort at all.

**Comment by eric-bixby** [comment]
Not sure it is related but I noticed the Bookmark Manager window does not always update/refresh. I had to close and reopen. 

The http to https issue sounds internal to Firefox. I’ll try searching for an existing FF bug.

**Comment by Hawkeye58** [comment]
Another couple of things I noticed are that when I select my sorts the colour of the selections changes to green and then I save them, but then when I go back into settings the colour is amber.
Are the colours correct or is that related to my fault?

Also, when I boot up in the morning and I check my sort selections, they have reverted back to the default settings and I have to change them again, surely that must be a fault?

**Comment by eric-bixby** [comment]
@Hawkeye58,
I need to document these, but yes, sounds correct.  You want them to be amber.

Here's what the preference text color means:
* Black = default value (saved).
* Green = changed, but not saved.
* Amber = changed and saved.
* Red = invalid value (not saved).

If the settings are clearing after rebooting, then something is clearing your browser's local storage.  Either Firefox itself or some other tool like CCleaner.  However, if this does not happen after restarting Firefox, then you must have some tool that does this during system startup.

**Comment by Hawkeye58** [comment]
I have the same settings in Firefox as I had in the version prior to Quantum which ran okay with your old version of Auto-sort and it never cleared the settings so can you suggest what might be clearing the settings in this version?

**Comment by Taurean75** [comment]
@Hawkeye58, listing your extensions and settings may help.

**Comment by Hawkeye58** [comment]
i only have 3 extensions...Auto-sort bookmarks, FoxClocks and Kaspersky Protection.

**Comment by Taurean75** [comment]
@Hawkeye58, you can rule out Kaspersky as I also have it with no apparent problems.

Something may be clearing local storage.

**Comment by eric-bixby** [comment]
Sorry, I'm closing this issue because it's old and I wasn't able to reproduce it.  Most likely something was clearing the cache/storage.
