### ISSUE TITLE
Translation not saved across sessions, Export button not working

### ISSUE THREAD

**Issue by MeiGuddet** [eric-bixby/auto-sort-bookmarks-webext#68]
I made my translation to German and saved it, but after FF restart all is gone.
Also it isn't possible to export the settings/translation, because the button doesn't work (no reaction when clicking on it). However Import button is working.

**Comment by eric-bixby** [comment]
I have a fix for this.  Just need to add "downloads" to the requested permissions for the add-on.

**Comment by eric-bixby** [comment]
Export button fixed in version 3.3.2.
