### ISSUE TITLE
sort by last modified does not work

### ISSUE THREAD

**Issue by yennor** [eric-bixby/auto-sort-bookmarks-webext#72]
I'm trying to sort the bookmarks in a certain folder by last modified. but it doesn't seem to work. When I add a second order constraint, it always gets ordered by the second constraint, seems like they've all got the same last modified date?

**Comment by Taurean75** [comment]
Maybe it's related to #69?

**Comment by sirbogs** [comment]
I am also having this issue ... can no longer sort by last modified
I would prefer last visited but ....

**Comment by eric-bixby** [comment]
Already resolved.

**Comment by sirbogs** [comment]
Resolve and working great thanks
:)
