### ISSUE TITLE
Settings open each time Firefox starts

### ISSUE THREAD

**Issue by daVe55w** [eric-bixby/auto-sort-bookmarks-webext#78]
Each time Firefox x64 (latest version) starts, Auto-sort Bookmarks Options open.  How do I stop this from occuring?

**Comment by shangles** [comment]
There is already a thread for this:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/issues/71

**Comment by eric-bixby** [comment]
@shangles 👍 

Closing this issue in favor of issue #71
