### ISSUE TITLE
Folder Configuration: Excluding folder bookmark toolbar does not work

### ISSUE THREAD

**Issue by Metal-Frog** [eric-bixby/auto-sort-bookmarks-webext#83]
I' tried to exclude the bookmark toolbar in FireFox from automatic sorting. But the extension ignores this. And furthermore the settings isn't saved at all ...

**Comment by eric-bixby** [comment]
What version of Firefox are you using?

**Comment by Metal-Frog** [comment]
Always the latest :)
Currently DevEdition 62.0b20 (64-Bit)

**Comment by JcChimjj** [comment]
＃83

**Comment by eric-bixby** [comment]
Duplicate of #75
