### ISSUE TITLE
Translation to brazilian portuguese

### ISSUE THREAD

**Issue by Felipefpl** [eric-bixby/auto-sort-bookmarks-webext#84]
Made an issue as you requested. ;)

[Brazilian Portuguese.zip](https://github.com/eric-bixby/auto-sort-bookmarks-webext/files/2476500/Brazilian.Portuguese.zip)

**Comment by eric-bixby** [comment]
Thanks for your contribution.  It's been added to version 3.3.2.

**Comment by Felipefpl** [comment]
Thank you for that. Btw, i got the newest version and i didnt find any place where i could select the option to change the language to pt-br, i also searched main page here to see if there was a wiki or something that showed how to do it. Is there a place for that?

**Comment by eric-bixby** [comment]
I added an entry to the FAQ:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/wiki/Frequently-Asked-Questions-(FAQ)

**Comment by Felipefpl** [comment]
Hell, i'm ashamed of myself, idk how i didnt see the entry to the wiki on top.... :/

Thank you for the help with this. It worked.

**Comment by eric-bixby** [comment]
Actually, I added it in response to your question, so no worries.  Glad you got it working.
