### ISSUE TITLE
Auto-Sort Bookmarks update requires new permissions

### ISSUE THREAD

**Issue by Arman-2** [eric-bixby/auto-sort-bookmarks-webext#88]
Hi,

I use Auto-Sort Bookmarks version 3.3 in Firefox v64.0.2. Great add-in! Thanks for all the effort.
But now, I get a warning when a new update is available for installation: 'It requires your permission to: download files and read an modify the browser's download history.'
Why does the add-in require these permissions?

Regards, Arman

![01](https://user-images.githubusercontent.com/35601784/51479797-a490e980-1d8f-11e9-902e-37426a38a6da.jpg)

**Comment by eric-bixby** [comment]
I have a wiki page that explains the permissions used:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/wiki/Permissions

Version 3.3.1 needed the "download" permission so that translations could be saved to a file.
