### ISSUE TITLE
Can I add Japanese to this add-on language?

### ISSUE THREAD

**Issue by Shitennouji** [eric-bixby/auto-sort-bookmarks-webext#89]
Thank you for this add-on.
It works as expected.
For me, it is one of my favorite addons.

by the way,
This add-on is not available in Japanese. It is a barrier for Japanese who dislike applications in different languages.
If possible, I will cooperate in translating into Japanese.

**Comment by eric-bixby** [comment]
@Shitennouji, I'm glad to hear that.  I will be happy to include your translation.  You can either email it, paste it in the reply, or create a "Pull Request".

**Comment by eric-bixby** [comment]
Actually, I would suggest not doing a "Pull Request" because the exported file is in a different format than the included translations.  Therefore, just send it to me and I will handle that part.

**Comment by Shitennouji** [comment]
I understood the requirement.
A few days later I will send you a translation (English> Japanese) by e-mail.

**Comment by Shitennouji** [comment]
I replied by e-mail. However, it says "noreply" and it seems that you can not get in touch normally.
Therefore, I post to this thread.

about:addons
Auto-sort：自動並べ替え
Delay：遅延する
Delay for Folders:フォルダの遅延
Case insensitive：大文字と小文字を区別しない
Folders to Sort：並べ替えをするフォルダ
Configure Folders：フォルダを構成する
Sort By：並び替え
Name：名称
URL：URL
Description：説明
Keyword：キーワード
Date Added：追加日
Last Modified=最終更新日時
Last visited=最終訪問日時
Visited count=訪問回数
Reversed URL=URL の逆順
Inverse Order：逆順
Then Sort By：並べ替え
None：無し

Inverse Second Order：2番目の順序を逆にする
Sort Folder By：フォルダ別で並び替え
Inverse Folder Order：フォルダの逆順
Folder Sort Order：フォルダの並べ替え順
Smart Bookmark Sort Order：スマートブックマークの並べ替え順序
Bookmark Sort Order：ブックマークの並べ替え順序


README.md
https://github.com/eric-bixby/auto-sort-bookmarks-webext

Provides a way to sort bookmarks automatically or manually.
ブックマークを自動または手動で並べ替え（以下、ソート）する方法を提供します。

This extension considers separators by sorting bookmarks between separators. However, set the delay before sorting (Inactivity Wait) to 45 seconds as the auto-sorting may happen while dragging bookmarks. This add-on cannot detect when bookmarks are being dragged.
この拡張機能は、区切り文字間でブックマークをソートすることによって区切り文字を考慮します。ただし、ブックマークをドラッグしている間は自動ソートが行われる可能性があるため、ソートまでの遅延時間（Inactivity Wait）を45秒に設定してください。このアドオンは、ブックマークがドラッグされていることを検出できません。

Backup your current bookmarks in case you do not like the new bookmarks order. To restore bookmarks, use Firefox's Bookmark Manager (click on Bookmarks menu, select Show All Bookmarks, then click on "Z" icon, select Restore, and select restore point based on date/time).
新しいブックマークの順序が気に入らない場合に備えて、現在のブックマークをバックアップしておくことをお勧めします。ブックマークを復元するには、Firefoxのブックマークマネージャを使用します（[ブックマーク]メニューをクリックし、[すべてのブックマークを表示]をクリックして[Z]アイコンをクリックし、[復元]をクリックします）。

Reviewers: Your constructive feedback is appreciated. However, if you need technical support, discover a bug, or have a feature request, then write an issue on the support site.
レビューア：あなたの建設的なフィードバックは大歓迎です。ただし、テクニカルサポートが必要な場合や、バグの発見、機能のリクエストなどは、[サポートサイト](https://github.com/eric-bixby/auto-sort-bookmarks-webext/issues)に課題（issue）を書いてください。

Settings:
設定：
● Auto-sort: If this option is enabled, the bookmarks will be sorted when bookmarks are added, changed, moved or deleted.
● 自動ソート：このオプションを有効にすると、ブックマークが追加、変更、移動、削除されたときにブックマークがソートされます。

● Inactivity Wait: Specifies how long to wait (in seconds) for inactivity before sorting bookmarks. This applies to automatic and manual sorting. A minimum value of 3 and a maximum of 255. Recommend
using a value of at least 45 if you move bookmarks by dragging.
● Inactivity Wait：ブックマークをソートする前に非アクティブを待つ時間を秒単位で指定します。これは自動ソートと手動ソートに適用されます。最小値は3、最大値は255です。ドラッグしてブックマークを移動する場合は、少なくとも45の値を使用することをお勧めします。

● Case Insensitive: If this option is enabled, the bookmarks will be sorted without considering the letter case.
● 大文字と小文字を区別しない：このオプションを有効にすると、大文字と小文字を区別せずにブックマークがソートされます。

● Sort By: Specifies the first sort criteria to sort the bookmarks.
● ソート順：ブックマークをソートするための最初のソート基準を指定します。

● Inverse Order: if this option is enabled, the order specified in 'Sort By' will be reversed. So the order will be descending.
● 逆順：このオプションを有効にすると、[並べ替え]で指定した順序が逆になります。そのため、順序は降順になります。

● Then Sort By: Specifies the second sort criteria to sort the bookmarks.
● 次にソート順：ブックマークをソートするための2番目のソート基準を指定します。

● Inverse Second Order: If this option is enabled, the order specified in 'Then Sort By' will be reversed.
● 2番目の順序を逆にする：このオプションを有効にすると、[ソート順]で指定した順序が逆になります。

● Sort Folder By: Specifies sort criteria to sort folders.
● フォルダのソート順：フォルダをソートするためのソート基準を指定します。

● Inverse Folder Order: If this option is enabled, the order specified in 'Sort Folder By' will be reversed.
● フォルダの順序を逆にする：このオプションを有効にすると、[フォルダのソート順]で指定した順序が逆になります。

● Folder Sort Order: Specifies the folder sort order. A minimum value of 1 and a maximum of 2.
● フォルダの並び順：フォルダの並び順を指定します。 最小値1、最大値2。

● Bookmark Sort Order: Specifies the bookmark sort order. A minimum value of 1 and a maximum of 2.
● ブックマークのソート順：ブックマークのソート順を指定します。最小値1、最大値2。

● Configure Folders: This button opens a new tab allowing you to exclude folders when sorting. If you uncheck the checkbox next to a folder, it won't be sorted, but the children folders will be sorted. If you want to exclude a folder recursively from being sorted, check the recursive checkbox.
● フォルダの設定：このボタンをクリックすると新しいタブが開き、ソート時にフォルダを除外できます。フォルダの横にあるチェックボックスをオフにすると、そのフォルダはソートされませんが、子フォルダはソートされます。フォルダを並べ替えから再帰的に除外する場合は、再帰的チェックボックスをオンにします。

**Comment by eric-bixby** [comment]
Yes, that's fine, thanks.  I'm working on it.

**Comment by eric-bixby** [comment]
@Shitennouji:
You translated the README and description pages, however, there's a file used by the add-on that has a few words or sentences not covered.
Would you please review what I have so far and help translate the parts that are still in English?
----
{
  "weh_prefs_label_auto_sort": {
    "message": "自動ソート："
  },
  "weh_prefs_description_auto_sort": {
    "message": "このオプションを有効にすると、ブックマークが追加、変更、移動、削除されたときにブックマークがソートされます。"
  },
  "weh_prefs_label_delay": {
    "message": "非アクティブ待ち："
  },
  "weh_prefs_description_delay": {
    "message": "ブックマークをソートする前に非アクティブを待つ時間を秒単位で指定します。これは自動ソートと手動ソートに適用されます。最小値は3、最大値は255です。ドラッグしてブックマークを移動する場合は、少なくとも45の値を使用することをお勧めします。"
  },
  "weh_prefs_label_case_insensitive": {
    "message": "大文字と小文字を区別しない："
  },
  "weh_prefs_description_case_insensitive": {
    "message": "このオプションを有効にすると、大文字と小文字を区別せずにブックマークがソートされます。"
  },
  "weh_prefs_label_sort_by": {
    "message": "ソート順："
  },
  "weh_prefs_description_sort_by": {
    "message": "ブックマークをソートするための最初のソート基準を指定します。"
  },
  "weh_prefs_label_inverse": {
    "message": "逆順："
  },
  "weh_prefs_description_inverse": {
    "message": "このオプションを有効にすると、[並べ替え]で指定した順序が逆になります。そのため、順序は降順になります。"
  },
  "weh_prefs_label_then_sort_by": {
    "message": "次にソート順："
  },
  "weh_prefs_description_then_sort_by": {
    "message": "ブックマークをソートするための2番目のソート基準を指定します。"
  },
  "weh_prefs_label_then_inverse": {
    "message": "2番目の順序を逆にする："
  },
  "weh_prefs_description_then_inverse": {
    "message": "このオプションを有効にすると、[ソート順]で指定した順序が逆になります。"
  },
  "weh_prefs_label_folder_sort_by": {
    "message": "フォルダのソート順："
  },
  "weh_prefs_description_folder_sort_by": {
    "message": "フォルダをソートするためのソート基準を指定します。"
  },
  "weh_prefs_label_folder_inverse": {
    "message": "フォルダの順序を逆にする："
  },
  "weh_prefs_description_folder_inverse": {
    "message": "このオプションを有効にすると、[フォルダのソート順]で指定した順序が逆になります。"
  },
  "weh_prefs_label_folder_sort_order": {
    "message": "フォルダの並び順："
  },
  "weh_prefs_description_folder_sort_order": {
    "message": "フォルダの並び順を指定します。 最小値1、最大値2。"
  },
  "weh_prefs_label_bookmark_sort_order": {
    "message": "ブックマークのソート順："
  },
  "weh_prefs_description_bookmark_sort_order": {
    "message": "ブックマークのソート順を指定します。最小値1、最大値2。"
  },
  "title": {
    "message": "Auto-Sort Bookmarks"
  },
  "settings": {
    "message": "設定"
  },
  "translation": {
    "message": "翻訳"
  },
  "configure_folders": {
    "message": "フォルダの設定"
  },
  "sort": {
    "message": "Sort"
  },
  "save": {
    "message": "Save"
  },
  "cancel": {
    "message": "Cancel"
  },
  "default": {
    "message": "Default"
  },
  "folders_to_sort": {
    "message": "Folders to Sort:"
  },
  "uncheck_to_exclude_folder": {
    "message": "Uncheck the folders to exclude when sorting."
  },
  "recursive": {
    "message": "Recursive"
  },
  "subfolders_recursively_excluded": {
    "message": "The sub-folders are recursively excluded."
  },
  "loading": {
    "message": "Loading..."
  }
}
----

**Comment by Shitennouji** [comment]
{
"weh_prefs_label_auto_sort": {
"message": "自動ソート："
},
"weh_prefs_description_auto_sort": {
"message": "このオプションを有効にすると、ブックマークが追加、変更、移動、削除されたときにブックマークがソートされます。"
},
"weh_prefs_label_delay": {
"message": "非アクティブ待ち："
},
"weh_prefs_description_delay": {
"message": "ブックマークをソートする前に非アクティブを待つ時間を秒単位で指定します。これは自動ソートと手動ソートに適用されます。最小値は3、最大値は255です。ドラッグしてブックマークを移動する場合は、少なくとも45の値を使用することをお勧めします。"
},
"weh_prefs_label_case_insensitive": {
"message": "大文字と小文字を区別しない："
},
"weh_prefs_description_case_insensitive": {
"message": "このオプションを有効にすると、大文字と小文字を区別せずにブックマークがソートされます。"
},
"weh_prefs_label_sort_by": {
"message": "ソート順："
},
"weh_prefs_description_sort_by": {
"message": "ブックマークをソートするための最初のソート基準を指定します。"
},
"weh_prefs_label_inverse": {
"message": "逆順："
},
"weh_prefs_description_inverse": {
"message": "このオプションを有効にすると、[並べ替え]で指定した順序が逆になります。そのため、順序は降順になります。"
},
"weh_prefs_label_then_sort_by": {
"message": "次にソート順："
},
"weh_prefs_description_then_sort_by": {
"message": "ブックマークをソートするための2番目のソート基準を指定します。"
},
"weh_prefs_label_then_inverse": {
"message": "2番目の順序を逆にする："
},
"weh_prefs_description_then_inverse": {
"message": "このオプションを有効にすると、[ソート順]で指定した順序が逆になります。"
},
"weh_prefs_label_folder_sort_by": {
"message": "フォルダのソート順："
},
"weh_prefs_description_folder_sort_by": {
"message": "フォルダをソートするためのソート基準を指定します。"
},
"weh_prefs_label_folder_inverse": {
"message": "フォルダの順序を逆にする："
},
"weh_prefs_description_folder_inverse": {
"message": "このオプションを有効にすると、[フォルダのソート順]で指定した順序が逆になります。"
},
"weh_prefs_label_folder_sort_order": {
"message": "フォルダの並び順："
},
"weh_prefs_description_folder_sort_order": {
"message": "フォルダの並び順を指定します。 最小値 1、最大値 2。"
},
"weh_prefs_label_bookmark_sort_order": {
"message": "ブックマークのソート順："
},
"weh_prefs_description_bookmark_sort_order": {
"message": "ブックマークのソート順を指定します。最小値 1、最大値 2。"
},
"title": {
"message": "ブックマークを自動ソートする"
},
"settings": {
"message": "設定"
},
"translation": {
"message": "翻訳"
},
"configure_folders": {
"message": "フォルダの設定"
},
"sort": {
"message": "ソート"
},
"save": {
"message": "保存"
},
"cancel": {
"message": "取り消す"
},
"default": {
"message": "Default（規定）"
},
"folders_to_sort": {
"message": "ソートするフォルダ："
},
"uncheck_to_exclude_folder": {
"message": "並べ替え時に除外するフォルダのチェックを外します。"
},
"recursive": {
"message": "再帰的"
},
"subfolders_recursively_excluded": {
"message": "サブフォルダは再帰的に除外されます."
},
"loading": {
"message": "読み込み中..."
}
}

**Comment by eric-bixby** [comment]
Thanks, that was quick.  I checked it into GitHub.  Hopefully, I can post a new release shortly.  I need to resolve a compile error first.

**Comment by Shitennouji** [comment]
Likewise, I'm really thankful to you.
This Addon is very useful, so I felt that it would be more convenient for users if it was multilingual.
However, that seems to have put you a lot of hassle.
I thank you from the bottom of my heart.

**Comment by eric-bixby** [comment]
No worries. You did not cause. Any hassle. It’s a dependency this software has on other software. Ianyway, I was able to fix it.  I just need to test before releasing.

**Comment by eric-bixby** [comment]
@Shitennouji,
I have a beta release available.  Would you please help test it?
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.3.3beta1

Here are the steps to test it:
1) Download the .xpi using the URL above.
2) Enter "about:debugging" into the address-bar.
3) Select "Load Tempoorary Add-on" button.
4) Select the downloaded .xpi file.

**Comment by Shitennouji** [comment]
I started testing (Validity of the translation) the "v3.3.3beta1" file from Mar 24, 2019, but there are a lot of contents (Setting, folder setting, translation, sorting) to be verified, so it takes time to work.

On weekdays, private time is limited because I am engaged in work. Therefore, the reply is likely to be around the beginning of next week.

For now, Until the status report.

**Comment by Shitennouji** [comment]
Sorry I made you wait.
I scrutinized the test version "v3.3.3beta1".
For the Japanese translation, I found a point where I need to correct words and sentences.
Correction is a necessary part is about the following.

Auto-sort：自動ソート
Date Added：追加された日付
Reversed URL：URL の逆順
title：タイトル

● Inactivity Wait: Specifies how long to wait (in seconds) for inactivity before sorting bookmarks. This applies to automatic and manual sorting. A minimum value of 3 and a maximum of 255. Recommend
using a value of at least 45 if you move bookmarks by dragging.
● ソートまでの遅延時間：ブックマークをソートする前に非アクティブの待機時間を秒単位で指定します。これは自動ソートと手動ソートに適用されます。最小値は3、最大値は255です。ドラッグしてブックマークを移動する場合は、少なくとも45の値を使用することをお勧めします。

● Sort By: Specifies the first sort criteria to sort the bookmarks.
● ソート順：ブックマークをソートするための第一のソート基準を指定します。

● Then Sort By: Specifies the second sort criteria to sort the bookmarks.
● 第二のソート順：ブックマークをソートするための第二のソート基準を指定します。

README.md
https://github.com/eric-bixby/auto-sort-bookmarks-webext
Backup your current bookmarks in case you do not like the new bookmarks order. To restore bookmarks, use Firefox's Bookmark Manager (click on Bookmarks menu, select Show All Bookmarks, then click on "Z" icon, select Restore, and select restore point based on date/time).
新しいブックマークの順序が気に入らない場合に備えて、現在のブックマークをバックアップしておくことをお勧めします。ブックマークを復元するには、Firefoxのブックマークマネージャを使用します（[ブックマーク]メニューをクリックし、[すべてのブックマークを表示]をクリックして "Z" アイコンをクリックし、[復元]をクリックします）。

**Comment by Shitennouji** [comment]
Sorry I made you wait.
I scrutinized the test version "v3.3.3beta1".
For the Japanese translation, I found a point where I need to correct words and sentences.
Correction is a necessary part is about the following.

Auto-sort：自動ソート
Date Added：追加された日付
Reversed URL：URL の逆順
title：タイトル
-------------------------------------------------------------------------------------------------------------------
{
"weh_prefs_label_auto_sort": {
"message": "自動ソート："
},
"weh_prefs_description_auto_sort": {
"message": "このオプションを有効にすると、ブックマークが追加、変更、移動、削除されたときにブックマークがソートされます。"
},
"weh_prefs_label_delay": {
"message": "ソートまでの遅延時間："
},
"weh_prefs_description_delay": {
"message": "ブックマークをソートする前に非アクティブの遅延時間を秒単位で指定します。これは自動ソートと手動ソートに適用されます。最小値は3、最大値は255です。ドラッグしてブックマークを移動する場合は、少なくとも45の値を使用することをお勧めします。"
},
"weh_prefs_label_case_insensitive": {
"message": "大文字と小文字を区別しない："
},
"weh_prefs_description_case_insensitive": {
"message": "このオプションを有効にすると、大文字と小文字を区別せずにブックマークがソートされます。"
},
"weh_prefs_label_sort_by": {
"message": "ソート順："
},
"weh_prefs_description_sort_by": {
"message": "ブックマークをソートするための第一のソート基準を指定します。"
},
"weh_prefs_label_inverse": {
"message": "逆順："
},
"weh_prefs_description_inverse": {
"message": "このオプションを有効にすると、[並べ替え]で指定した順序が逆になります。そのため、順序は降順になります。"
},
"weh_prefs_label_then_sort_by": {
"message": "第二のソート順："
},
"weh_prefs_description_then_sort_by": {
"message": "ブックマークをソートするための第二のソート順ソート基準を指定します。"
},
"weh_prefs_label_then_inverse": {
"message": "2番目の順序を逆にする："
},
"weh_prefs_description_then_inverse": {
"message": "このオプションを有効にすると、[ソート順]で指定した順序が逆になります。"
},
"weh_prefs_label_folder_sort_by": {
"message": "フォルダのソート順："
},
"weh_prefs_description_folder_sort_by": {
"message": "フォルダをソートするためのソート基準を指定します。"
},
"weh_prefs_label_folder_inverse": {
"message": "フォルダの順序を逆にする："
},
"weh_prefs_description_folder_inverse": {
"message": "このオプションを有効にすると、[フォルダのソート順]で指定した順序が逆になります。"
},
"weh_prefs_label_folder_sort_order": {
"message": "フォルダの並び順："
},
"weh_prefs_description_folder_sort_order": {
"message": "フォルダの並び順を指定します。 最小値 1、最大値 2。"
},
"weh_prefs_label_bookmark_sort_order": {
"message": "ブックマークのソート順："
},
"weh_prefs_description_bookmark_sort_order": {
"message": "ブックマークのソート順を指定します。最小値 1、最大値 2。"
},
"title": {
"message": "ブックマークを自動ソートする"
},
"settings": {
"message": "設定"
},
"translation": {
"message": "翻訳"
},
"configure_folders": {
"message": "フォルダの設定"
},
"sort": {
"message": "ソート"
},
"save": {
"message": "保存"
},
"cancel": {
"message": "取り消す"
},
"default": {
"message": "Default（規定）"
},
"folders_to_sort": {
"message": "ソートするフォルダ："
},
"uncheck_to_exclude_folder": {
"message": "並べ替え時に除外するフォルダのチェックを外します。"
},
"recursive": {
"message": "再帰的"
},
"subfolders_recursively_excluded": {
"message": "サブフォルダは再帰的に除外されます."
},
"loading": {
"message": "読み込み中..."
}
}
-------------------------------------------------------------------------------------------------------------------
README.md
https://github.com/eric-bixby/auto-sort-bookmarks-webext
Backup your current bookmarks in case you do not like the new bookmarks order. To restore bookmarks, use Firefox's Bookmark Manager (click on Bookmarks menu, select Show All Bookmarks, then click on "Z" icon, select Restore, and select restore point based on date/time).
新しいブックマークの順序が気に入らない場合に備えて、現在のブックマークをバックアップしておくことをお勧めします。ブックマークを復元するには、Firefoxのブックマークマネージャを使用します（[ブックマーク]メニューをクリックし、[すべてのブックマークを表示]をクリックして "Z" アイコンをクリックし、[復元]をクリックします）。

**Comment by eric-bixby** [comment]
Ok, I posted a new beta release.

**Comment by Shitennouji** [comment]
Right away,
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases
I checked the beta version "Version 3.4 Beta1".

Although it was slight, I found an uncorrected part.
Uncorrected parts are **_# 1_** and **_# 2_** below.

**_#1_**：
"weh_prefs_label_delay": {
"message": "ソートまでの遅延時間："
},
"weh_prefs_description_delay": {
"message": "ブックマークをソートする前に非アクティブの遅延時間を秒単位で指定します。これは自動ソートと手動ソートに適用されます。最小値は3、最大値は255です。ドラッグしてブックマークを移動する場合は、少なくとも45の値を使用することをお勧めします。"

**_#2_**：
"weh_prefs_label_then_sort_by": {
"message": "第二のソート順："
},
"weh_prefs_description_then_sort_by": {
"message": "ブックマークをソートするための第二のソート順ソート基準を指定します。"

**Comment by eric-bixby** [comment]
OK, another beta for you.

**Comment by Shitennouji** [comment]
I checked the beta version "Version 3.4 Beta2".
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.4beta2
If this test version, is OK.
This is completed. Thank you very much.
