### ISSUE TITLE
bug excluded folders

### ISSUE THREAD

**Issue by ghost** [eric-bixby/auto-sort-bookmarks-webext#93]
Using FF 67, e10s disabled, the plugin don't save my folders settings.

**Comment by eric-bixby** [comment]
@mrochaaa,
e10s, is that multi-processor support?  I tried single and multi-processor, the settings saved regardless.
Do you see any errors in the Firefox web console?
67 is kind of old, have you tried 68.0.2?

**Comment by eric-bixby** [comment]
Closed due to not enough information.
