### ISSUE TITLE
How about a most recent visit option and maybe a sort now button

### ISSUE THREAD

**Issue by sirbogs** [eric-bixby/auto-sort-bookmarks-webext#95]
How about a most recent visit option and maybe a sort now button
More details:
auto-sort bookmark 3.4
I am wanting to auto sort in bookmarks not in the bookmark library (two different places)
I do not see an auto-sort bookmark the last visited as an option ...
For that matter I do not see a sort now button available in auto-sort bookmark options
Direct contact info => sirbogs (at) hotmail.com

**Comment by avenmore** [comment]
There was an option to sort by "Last Visited" in 3.3, but seems to have disappeared in 3.4. I've reverted to the older version.

**Comment by sirbogs** [comment]
How to you go back to previous version ...I get unverified cannot install

**Comment by avenmore** [comment]
From the [versions](https://addons.mozilla.org/en-US/firefox/addon/auto-sort-bookmarks/versions/) page. Did you mean to close this issue?

**Comment by eric-bixby** [comment]
This new issue is cover by item #97.
