### ISSUE TITLE
Sort by Last visited missing in new version

### ISSUE THREAD

**Issue by sirbogs** [eric-bixby/auto-sort-bookmarks-webext#97]
Hi
Any chance in getting option to sort by "Last Visited" returned in future version? Disappeared in 3.4

**Comment by eric-bixby** [comment]
This issue was previously mentioned in item #95.  I'm able to reproduce it.  This feature accidentally got removed when sort by host-name was added.

**Comment by eric-bixby** [comment]
@sirbogs:
I have a beta release available for testing if you want to try it:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.4.1beta4
