### ISSUE TITLE
Multiple Issues -- http://ericbixby.com => https://eric-bixby.github.io

### ISSUE THREAD

**Issue by bradsmithsite** [eric-bixby/auto-sort-bookmarks-webext#98]
https://ericbixby.com/, your domain has expired.

Hello, your AutoSort Bookmark addon has a few bugs:
- When you add a separator to the main bookmark toolbar, it doesn't always sort the bookmarks separated by the separator.
- There is also a problem with FireFox Sync, sometimes it adds duplicate separators. Not sure if this is a bug with your addon or Firefox.
- On your Firefox Addon page I have you a 5 rating because it's an absolutely excellent addon.

Please e-mail me at bradsmithsite@gmail.com and let me know if you've found the bug.

Again, thank you for your excellent addon!

King regards,
Brad Smith.

**Comment by eric-bixby** [comment]
@bradsmithsite,

Thanks for reminding me about the expired domain.  It's just a place holder for now, but now it's:
https://eric-bixby.github.io/

Usually, separator problems are a timing issue; the user/browser and the add-on are trying to change things at the same time, but I'll check it out.

I don't use Firefox Sync myself, but I check that too.

Thanks for the 5 star, glad you like it.

**Comment by bradsmithsite** [comment]
Thanks for looking into it. Appreciate it.

 

Also, thank you so much for your fantastic add-on!

 

Keep well!

 

King regards,

 


  <file:///C:/Users/User/AppData/Roaming/Microsoft/Signatures/Brad%20Smith%20(Doropie).jpg> 

Brad Smith


Designation:

Software Developer


Cellphone:

+27 82 481 0098


Telephone:

+27 11 814 7895


E-mail:

 <mailto:brad@doropie.com> brad@doropie.com


Web Site:

http://doropie.com/

**Comment by eric-bixby** [comment]
@bradsmithsite,

For the "added separator" issue, what are the steps?  For example, are you using the sidebar or the bookmark manager (show all bookmarks)? How are you adding the separator, right-mouse click? etc..

For the "duplicate separator" issue, I'm pretty sure that's a FirefoxSync issue.  I've also seen that happen when using EverHelper/EverSync add-on.  During the merge/sync, it thinks they are unique rather than duplicates.  I'm guessing it has to do with the modification date/time of the separator.

**Comment by bradsmithsite** [comment]
Will record you video sometime today.

 

Regards,

 


  <file:///C:/Users/User/AppData/Roaming/Microsoft/Signatures/Brad%20Smith%20(Doropie).jpg> 

Brad Smith


Designation:

Software Developer


Cellphone:

+27 82 481 0098


Telephone:

+27 11 814 7895


E-mail:

 <mailto:brad@doropie.com> brad@doropie.com


Web Site:

http://doropie.com/

**Comment by eric-bixby** [comment]
Closed.  Unable to reproduce.
