### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by MeiGuddet** [eric-bixby/auto-sort-bookmarks-webext#99]
The German translation is not nearly complete. So I have revised it. Can you please add it to your add-on? I named it messages_de.json and zipped it:
[messages_de.zip](https://github.com/eric-bixby/auto-sort-bookmarks-webext/files/4026808/messages_de.zip)

**Comment by eric-bixby** [comment]
Great, thanks. I’ll work on it this weekend.

**Comment by eric-bixby** [comment]
@MeiGuddet,
I've pushed a beta release.  Would you please try it and confirm it looks correct?
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.4.1beta1

BTW, sorry for the delay, I got sick and then forgot about finishing this.

**Comment by MeiGuddet** [comment]
@eric-bixby, I made three wrong/misleading translations. Here are my corrections:
Line 41
`  "weh_prefs_description_auto_sort": {
    "message": "Ist diese Option aktiviert, werden die Lesezeichen beim Hinzufügen, Ändern, Verschieben oder Löschen sortiert. D. h., Sie können keine Lesezeichen im selben Ordner verschieben, es sei denn, sie werden über ein Trennzeichen verschoben."`
Line 62
`  "weh_prefs_description_inverse": {
    "message": "Wenn diese Option aktiviert ist, wird die in 'Sortieren nach' angegebene Reihenfolge umgekehrt. Die Reihenfolge ist dann absteigend."`
Line 107
`  "weh_prefs_label_then_inverse": {
    "message": "2. Reihenfolge umkehren:"`

Everything else is fine. Thank you very much :ok_hand:

**Comment by eric-bixby** [comment]
@MeiGuddet:
Here's the latest version with your corrections:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.4.1beta2

**Comment by MeiGuddet** [comment]
Just one thing left, then all is fine:
Line 29
"subfolders_recursively_excluded": { "message": "Unterordner werden rekursiv ausgeschlossen." },
The word "Die" in front of "Unterordner" needs to be removed.

**Comment by eric-bixby** [comment]
@MeiGuddet:
Here's the latest version with your corrections:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.4.1beta3

**Comment by MeiGuddet** [comment]
That's it, In Waterfox everything looks ok.
In FF still not possible, because it's not verified.

**Comment by eric-bixby** [comment]
In Firefox, here's the procedure for testing:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/wiki/Debug-Test-Process
